[package]
name = "event_model_table_creator"
version = "0.1.0"
authors = ["fullstackgjj <fullstackgjj@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
